# Generated by Django 4.2.6 on 2023-10-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garden_planner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant_info",
            name="YVR_in_seedDate_start",
            field=models.DateTimeField(
                null=True, verbose_name="Earliest indoor seed starting date"
            ),
        ),
        migrations.AddField(
            model_name="plant_info",
            name="YVR_in_seedDate_stop",
            field=models.DateTimeField(
                null=True, verbose_name="Latest indoor seed starting date"
            ),
        ),
        migrations.AddField(
            model_name="plant_info",
            name="YVR_out_seedDate_start",
            field=models.DateTimeField(
                null=True, verbose_name="Earliest outdoor seed starting date"
            ),
        ),
        migrations.AddField(
            model_name="plant_info",
            name="YVR_out_seedDate_stop",
            field=models.DateTimeField(
                null=True, verbose_name="Latest outdoor seed starting date"
            ),
        ),
        migrations.AddField(
            model_name="plant_info",
            name="YVR_tpDate_start",
            field=models.DateTimeField(
                null=True, verbose_name="Earliest transplant date"
            ),
        ),
        migrations.AddField(
            model_name="plant_info",
            name="YVR_tpDate_stop",
            field=models.DateTimeField(
                null=True, verbose_name="Latest transplant date"
            ),
        ),
    ]
