# Generated by Django 4.2.6 on 2023-10-12 21:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garden_planner", "0002_plant_info_yvr_in_seeddate_start_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plant_info",
            old_name="plant_type",
            new_name="plant_name",
        ),
        migrations.RenameField(
            model_name="seed_inventory",
            old_name="plant_type",
            new_name="plant_name",
        ),
    ]
