# Generated by Django 4.2.6 on 2023-10-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garden_planner", "0003_rename_plant_type_plant_info_plant_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant_info",
            name="plant_family",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
