# Generated by Django 4.2.6 on 2023-10-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garden_planner", "0004_plant_info_plant_family"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant_info",
            name="YVR_in_seedDate_start",
            field=models.DateField(
                null=True, verbose_name="Earliest indoor seed starting date"
            ),
        ),
        migrations.AlterField(
            model_name="plant_info",
            name="YVR_in_seedDate_stop",
            field=models.DateField(
                null=True, verbose_name="Latest indoor seed starting date"
            ),
        ),
        migrations.AlterField(
            model_name="plant_info",
            name="YVR_out_seedDate_start",
            field=models.DateField(
                null=True, verbose_name="Earliest outdoor seed starting date"
            ),
        ),
        migrations.AlterField(
            model_name="plant_info",
            name="YVR_out_seedDate_stop",
            field=models.DateField(
                null=True, verbose_name="Latest outdoor seed starting date"
            ),
        ),
        migrations.AlterField(
            model_name="plant_info",
            name="YVR_tpDate_start",
            field=models.DateField(null=True, verbose_name="Earliest transplant date"),
        ),
        migrations.AlterField(
            model_name="plant_info",
            name="YVR_tpDate_stop",
            field=models.DateField(null=True, verbose_name="Latest transplant date"),
        ),
        migrations.AlterField(
            model_name="plant_info",
            name="pub_date",
            field=models.DateField(verbose_name="date added to DB"),
        ),
        migrations.AlterField(
            model_name="seed_inventory",
            name="pub_date",
            field=models.DateField(verbose_name="date added to DB"),
        ),
    ]
