# Generated by Django 4.2.6 on 2023-10-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garden_planner", "0006_alter_plant_info_yvr_in_seeddate_start_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant_info",
            name="plant_family",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
