# Generated by Django 4.2.6 on 2023-10-12 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("garden_planner", "0010_plant_info_plant_family"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plant_families",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("family_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="plant_info",
            name="plant_family",
        ),
        migrations.AddField(
            model_name="plant_info",
            name="family_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="garden_planner.plant_families",
            ),
        ),
    ]
