# Generated by Django 4.2.6 on 2023-10-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garden_planner", "0012_seed_inventory_seed_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="seed_inventory",
            name="seed_link",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="seed_inventory",
            name="seed_year",
            field=models.PositiveSmallIntegerField(default=2023),
        ),
    ]
