# Generated by Django 4.2.6 on 2023-10-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garden_planner", "0013_seed_inventory_seed_link_seed_inventory_seed_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant_info",
            name="YVR_in_seedDate_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="Earliest indoor seed date"
            ),
        ),
        migrations.AlterField(
            model_name="plant_info",
            name="YVR_in_seedDate_stop",
            field=models.DateField(
                blank=True, null=True, verbose_name="Latest indoor seed date"
            ),
        ),
        migrations.AlterField(
            model_name="plant_info",
            name="YVR_out_seedDate_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="Earliest outdoor seed date"
            ),
        ),
        migrations.AlterField(
            model_name="plant_info",
            name="YVR_out_seedDate_stop",
            field=models.DateField(
                blank=True, null=True, verbose_name="Latest outdoor seed date"
            ),
        ),
    ]
