# Generated by Django 4.2.6 on 2023-10-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garden_planner", "0014_alter_plant_info_yvr_in_seeddate_start_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant_info",
            name="plants_per_sqf",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="Plants per square foot"
            ),
        ),
    ]
